Add files via upload

diff --git a/ani-jkm b/ani-jkm
--- a/ani-jkm
+++ b/ani-jkm
@@ -1,38 +1,157 @@
 #!/bin/bash
 
-## Setting site
-site=$(echo "https://gogoanime.film")
+## Made by OrangeXarot
+## for FunnySuperst56 (TheGamerMaxAC)
+##
 
-## Clearing name spaces
-query=$(echo "$*" | tr ' ' '+')
+## Bannner
+function banner(){
+    echo -e "$violet   __    _  _  ____ $colnull    $blue  ____  _  _  __  __ $colnull"
+    echo -e "$violet  /__\  ( \( )(_  _)\e[0m___$blue  (_  _)( )/ )(  \/  )$colnull"
+    echo -e "$violet /(__)\  )  (  _)(_$colnull(___)$blue.-_)(   )  (  )    ( $colnull"
+    echo -e "$violet(__)(__)(_)\_)(____)$colnull   $blue \____) (_)\_)(_/\/\_)$colnull"
+    echo ""
+}
+## settings
+# colors
+red="\e[1;31m"
+green="\e[1;32m"
+brown="\e[1;33m" # (Yellow)
+blue="\e[1;34m"  # (Orange)
+violet="\e[1;35m"
+cyan="\e[1;36m"
+colnull="\e[0m"
 
-## Checking for name args
-if [ "$*" = "" ]
-then
-    read -p "Select anime: " query
-    query=$(echo "$query" | tr ' ' '+')
+# variables
+site=$(echo "https://gogoanime.film") # change when domain changes
+browser=$(echo "librewolf") # change browser for the one you are using
+
+if ! [ -d "~/.config/ani-jkm" ]; then
+    mkdir -p ~/.config/ani-jkm/
+    touch ~/.config/ani-jkm/history.txt
+    touch ~/.config/ani-jkm/favorites.txt
 fi
 
-if [ "$query" = "" ]
-then
-    echo "Empty input"
-    exit
-fi
+function searchAnime(){
+    ## Search Anime
+    read -p "Search anime: " search
+    [ -z "$search" ] &&  echo -e "$red Empty input (write 0 for going back)$colnull" && searchAnime
+    [ "$option" = "exit" ] && exit
+    [ "$search" -eq 0 ] &> /dev/null && menu
+    query=$(echo "$search" | tr ' ' '+')
 
-## Finding anime
-anime=$(curl -s "$site/search.html?keyword=$query" | grep -Eo "/category/[a-zA-Z0-9?%-]*" | head -n 1 | sed  "s/\/category\///g")
-name=$(echo "$anime" | tr '-' ' ')
-echo "Anime found: $name"
+    # Cleaning search input
+    anime=""
+    findAnime
+}
+function findAnime(){
+    # Finding anime
+    [ -z "$anime" ] && anime=$(curl -s "$site/search.html?keyword=$query" | grep -Eo "/category/[a-zA-Z0-9?%-]*" | head -n 1 | sed  "s/\/category\///g")
+    [ -z "$anime" ] && echo -e "$red Nothing found$colnull" && searchAnime
+    name=$(echo "$anime" | tr '-' ' ')
+    echo -e "Anime found: $cyan$name$colnull"
+    animeOptions
+}
 
-## Fetching and selecting episodes
-episodes=$(curl -s "$site/category/$anime" | grep -Eo "0\-[0-9]*" | head -n 1 | sed "s/0-//g")
-read -p "Select episode (1-$episodes): " EP
+function episodeSelect(){
+    ## Fetching and selecting episodes
+    episodes=$(curl -s "$site/category/$anime" | grep -Eo "0\-[0-9]*" | sed "s/0-//g" | sort -unr | head -n1)
+    read -p "Select episode (1-$episodes): " EP
+    [ -z "$EP" ] && EP=1
+    [ "$EP" = "exit" ] && exit
+    [ "$EP" -eq 0 ] && animeOptions
+    [ "$EP" -eq 69 ] && echo -e "$brown nice$colnull"
+    [ "$EP" -gt "$episodes" ] && echo -e "$red The episode doesn\'t exist$colnull" && episodeSelect
+    streamEpisode
+}
 
-if [ "$EP" = "" ]
-then
-    EP=1
-fi
+function streamEpisode(){
+    ## finding stream and playing it in a browser
+    link=$(curl -s "$site/$anime-episode-$EP" | grep -Eo "fembed-hd.com/v/[a-z0-9-]*" | head -n1)
+    exec $browser "https://$link" &> /dev/null &
+    episodeCtrl
+}
 
-## finding stream and playing it in a browser
-link=$(curl -s "$site/$anime-episode-$EP" | grep -Eo "gogoplay.io/streaming.php?[a-zA-Z0-9?+&%=-]*"| head -n 1)
-exec librewolf "https://$link" &> /dev/null &
+function episodeCtrl(){
+    option=""
+    if [ "$EP" -eq 69 ]; then
+        echo -e "Whatching$violet episode $EP$colnull$brown (nice)$colnull of $cyan$name$colnull"; else
+        echo -e "Whatching$violet episode $EP$colnull of $cyan$name$colnull"; fi
+    echo -e "$blue 1 $colnull- Open next episode"
+    echo -e "$blue 2 $colnull- Open previous episode"
+    echo -e "$blue 0 $colnull- Go back to episode selection"
+    read -p "Select option (1): " option
+    [ -z "$option" ] && option=1
+    [ "$option" = "exit" ] && exit
+    [ "$option" -eq 1 ] && let "EP++" 
+    [ "$option" -eq 2 ] && let "EP--"
+    [ "$option" -eq 0 ] && episodeSelect
+    [ "$EP" -gt "$episodes" ] && echo -e "$red The episode doesn't exist$colnull" && let "EP--" && episodeCtrl
+    [ "$EP" -eq 0 ] && echo -e "$red The episode doesn't exist$colnull" && let "EP++" && episodeCtrl
+    streamEpisode
+}
+
+function listFav(){
+    num=""
+    list=$(sed '=' ~/.config/ani-jkm/favorites.txt | tr '-' ' ' | sed 'N; s/\n/\\e[0m - /' | sed 's/^/ \\e[1;34m/')
+    [ -z "$list" ] && echo "You have no favorites" && menu
+    echo "Favorites list - watch or remove an anime"
+    echo -e "$list"
+    echo -e "$blue 0 $colnull- go back"
+    read -p "Choose anime (1): " num
+    [ -z "$num" ] && num=1
+    [ "$num" = "exit" ] && exit
+    [ "$num" -eq 0 ] && menu
+    anime=$(cat ~/.config/ani-jkm/favorites.txt | sed -n -e "$num p")
+    [ -z "$anime" ] && echo "Invalid Number" && listFav
+    favOptions
+
+}
+
+function favOptions(){
+    option=""
+    name=$(echo "$anime" | tr '-' ' ')
+    echo -e "You selected $cyan$name$colnull, you can:"
+    echo -e "$blue 1 $colnull- watch it"
+    echo -e "$blue 2 $colnull- remove it "
+    echo -e "$blue 0 $colnull- go back"
+    read -p "Choose option (1): " option
+    [ -z "$option" ] && option=1
+    [ "$option" = "exit" ] && exit
+    [ "$option" -eq 1 ] && episodeSelect
+    [ "$option" -eq 2 ] && sed -i ~/.config/ani-jkm/favorites.txt -e "$num d" && listFav
+    [ "$option" -eq 0 ] && listFav
+    favOptions
+}
+
+
+function menu(){
+    option=""
+    echo -e "$blue 1 $colnull- Search an Anime"
+    echo -e "$blue 2 $colnull- List Favorite"
+    read -p "Choose option (1): " option
+    [ -z "$option" ] && option=1
+    [ "$option" = "exit" ] && exit
+    [ "$option" -eq 1 ] && searchAnime
+    [ "$option" -eq 2 ] && listFav
+    menu
+}
+
+function animeOptions(){
+    option=""
+    echo -e "$blue 1 $colnull- Watch"
+    echo -e "$blue 2 $colnull- Save in Favourites"
+    echo -e "$blue 0 $colnull- Go back"
+    read -p "Chose option (1): " option
+    [ -z "$option" ] && option=1
+    [ "$option" = "exit" ] && exit
+    [ "$option" -eq 1 ] && episodeSelect
+    [ "$option" -eq 2 ] && echo "$anime" >> ~/.config/ani-jkm/favorites.txt && listFav
+    [ "$option" -eq 0 ] && searchAnime
+    animeOptions
+
+}
+
+
+banner
+menu
